#baseURL = "https://mfreiholz.de"
#baseURL = "http://localhost:1337"
languageCode = "en-us"
title = "mfreiholz.de"
theme = "2022-05"
#relativeURLs = false
#disableLiveReload = true

[taxonomies]
tag = "tags"
